source 'https://rubygems.org'

gem 'activerecord', '~> 5.2', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sqlite3', '~>1.3.6'
gem 'sinatra'
gem 'thin'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'require_all'
gem 'faker'
